image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'obj'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  # 3) A relative path to the source code from project repository root.
  SOURCE_CODE_PATH: '*/*/'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'
  tags:
    - docker-shared

tests_exercise1:
  stage: test
  script:
    - 'dotnet test --no-restore --filter DisplayName~Exercise1'
  tags:
    - docker-shared

tests_exercise2:
  stage: test
  script:
    - 'dotnet test --no-restore --filter DisplayName~Exercise2'
  tags:
    - docker-shared

tests_exercise3:
  stage: test
  script:
    - 'dotnet test --no-restore --filter DisplayName~Exercise3'
  tags:
    - docker-shared

tests_exercise4:
  stage: test
  script:
    - 'dotnet test --no-restore --filter DisplayName~Exercise4'
  tags:
    - docker-shared

tests_exercise5:
  stage: test
  script:
    - 'dotnet test --no-restore --filter DisplayName~Exercise5'
  tags:
    - docker-shared